# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIFormCompanyInfo.ui'
#
# Created: Sun Jul 20 22:29:56 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormCompanyInfo(object):
    def setupUi(self, FormCompanyInfo):
        FormCompanyInfo.setObjectName(_fromUtf8("FormCompanyInfo"))
        FormCompanyInfo.resize(991, 594)
        self.tabWidget = QtGui.QTabWidget(FormCompanyInfo)
        self.tabWidget.setGeometry(QtCore.QRect(30, 10, 952, 585))
        self.tabWidget.setMinimumSize(QtCore.QSize(952, 585))
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setStatusTip(_fromUtf8(""))
        self.tabWidget.setWhatsThis(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.frame = QtGui.QFrame(self.tabWidgetPage2)
        self.frame.setGeometry(QtCore.QRect(280, 60, 341, 311))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 52, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEditBizName = QtGui.QLineEdit(self.frame)
        self.lineEditBizName.setGeometry(QtCore.QRect(130, 20, 142, 21))
        self.lineEditBizName.setObjectName(_fromUtf8("lineEditBizName"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 50, 55, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEditBizBossName = QtGui.QLineEdit(self.frame)
        self.lineEditBizBossName.setGeometry(QtCore.QRect(130, 50, 142, 21))
        self.lineEditBizBossName.setMaxLength(10)
        self.lineEditBizBossName.setObjectName(_fromUtf8("lineEditBizBossName"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 83, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEditBizNumber = QtGui.QLineEdit(self.frame)
        self.lineEditBizNumber.setGeometry(QtCore.QRect(130, 80, 142, 21))
        self.lineEditBizNumber.setObjectName(_fromUtf8("lineEditBizNumber"))
        self.lineEditBizEmail = QtGui.QLineEdit(self.frame)
        self.lineEditBizEmail.setGeometry(QtCore.QRect(130, 240, 142, 21))
        self.lineEditBizEmail.setObjectName(_fromUtf8("lineEditBizEmail"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(23, 116, 26, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_BizKind = QtGui.QLineEdit(self.frame)
        self.lineEdit_BizKind.setGeometry(QtCore.QRect(130, 178, 142, 21))
        self.lineEdit_BizKind.setObjectName(_fromUtf8("lineEdit_BizKind"))
        self.lineEditBizType = QtGui.QLineEdit(self.frame)
        self.lineEditBizType.setGeometry(QtCore.QRect(130, 116, 142, 21))
        self.lineEditBizType.setObjectName(_fromUtf8("lineEditBizType"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(23, 178, 26, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(23, 209, 93, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(23, 147, 60, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(23, 240, 83, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lineEditBizAddr = QtGui.QLineEdit(self.frame)
        self.lineEditBizAddr.setGeometry(QtCore.QRect(130, 147, 142, 21))
        self.lineEditBizAddr.setObjectName(_fromUtf8("lineEditBizAddr"))
        self.lineEdit_BizKind_2 = QtGui.QLineEdit(self.frame)
        self.lineEdit_BizKind_2.setGeometry(QtCore.QRect(130, 209, 142, 21))
        self.lineEdit_BizKind_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferUppercase)
        self.lineEdit_BizKind_2.setMaxLength(15)
        self.lineEdit_BizKind_2.setObjectName(_fromUtf8("lineEdit_BizKind_2"))
        self.label_7 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_7.setGeometry(QtCore.QRect(410, 20, 90, 32))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButtonSave = QtGui.QPushButton(self.tabWidgetPage2)
        self.pushButtonSave.setGeometry(QtCore.QRect(550, 20, 71, 32))
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.tabWidget.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.label_9 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_9.setGeometry(QtCore.QRect(380, 10, 97, 32))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pushButtonSaveUser = QtGui.QPushButton(self.tabWidgetPage1)
        self.pushButtonSaveUser.setGeometry(QtCore.QRect(610, 20, 87, 32))
        self.pushButtonSaveUser.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButtonSaveUser.setAutoFillBackground(True)
        self.pushButtonSaveUser.setObjectName(_fromUtf8("pushButtonSaveUser"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tabWidgetPage1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 50, 811, 151))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEditUserPhone = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditUserPhone.setObjectName(_fromUtf8("lineEditUserPhone"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditUserPhone)
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEditUserPosition = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditUserPosition.setObjectName(_fromUtf8("lineEditUserPosition"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditUserPosition)
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lineEditUserAddr = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditUserAddr.setObjectName(_fromUtf8("lineEditUserAddr"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditUserAddr)
        self.label_16 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_16)
        self.lineEditUserEtc = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditUserEtc.setObjectName(_fromUtf8("lineEditUserEtc"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditUserEtc)
        self.horizontalLayout_3.addLayout(self.formLayout_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_15 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.lineEditUserEmail = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditUserEmail.setObjectName(_fromUtf8("lineEditUserEmail"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditUserEmail)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEditUserName = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditUserName.setObjectName(_fromUtf8("lineEditUserName"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditUserName)
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.lineEditMinNumber = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditMinNumber.setObjectName(_fromUtf8("lineEditMinNumber"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditMinNumber)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.tableView = QtGui.QTableView(self.tabWidgetPage1)
        self.tableView.setGeometry(QtCore.QRect(50, 220, 821, 281))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.actionOnButtonEvent = QtGui.QAction(FormCompanyInfo)
        self.actionOnButtonEvent.setCheckable(True)
        self.actionOnButtonEvent.setObjectName(_fromUtf8("actionOnButtonEvent"))
        self.actionActionOnButtonUserSave = QtGui.QAction(FormCompanyInfo)
        self.actionActionOnButtonUserSave.setObjectName(_fromUtf8("actionActionOnButtonUserSave"))

        self.retranslateUi(FormCompanyInfo)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormCompanyInfo)

    def retranslateUi(self, FormCompanyInfo):
        FormCompanyInfo.setWindowTitle(_translate("FormCompanyInfo", "회사정보", None))
        self.label.setText(_translate("FormCompanyInfo", "사업자명  ", None))
        self.label_6.setText(_translate("FormCompanyInfo", "성명(이름)", None))
        self.label_2.setText(_translate("FormCompanyInfo", "사업자등록번호 ", None))
        self.label_3.setText(_translate("FormCompanyInfo", "업태 ", None))
        self.label_5.setText(_translate("FormCompanyInfo", "종목 ", None))
        self.label_8.setText(_translate("FormCompanyInfo", "전화번호 (연락처)", None))
        self.label_4.setText(_translate("FormCompanyInfo", "사업장 주소", None))
        self.label_17.setText(_translate("FormCompanyInfo", "회사대표 이메일", None))
        self.label_7.setText(_translate("FormCompanyInfo", "회사정보", None))
        self.pushButtonSave.setText(_translate("FormCompanyInfo", "저장", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("FormCompanyInfo", "회사정보", None))
        self.label_9.setText(_translate("FormCompanyInfo", "직원정보 ", None))
        self.pushButtonSaveUser.setText(_translate("FormCompanyInfo", "저장하기", None))
        self.label_14.setText(_translate("FormCompanyInfo", "핸드폰(연락처)", None))
        self.label_13.setText(_translate("FormCompanyInfo", "직책", None))
        self.label_12.setText(_translate("FormCompanyInfo", "주소(거주)", None))
        self.label_16.setText(_translate("FormCompanyInfo", "기타사항 ", None))
        self.label_15.setText(_translate("FormCompanyInfo", "이메일주소(google)", None))
        self.label_10.setText(_translate("FormCompanyInfo", "직원성명", None))
        self.label_11.setText(_translate("FormCompanyInfo", "주민등록번호", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("FormCompanyInfo", "직원정보", None))
        self.actionOnButtonEvent.setText(_translate("FormCompanyInfo", "onButtonEvent", None))
        self.actionOnButtonEvent.setToolTip(_translate("FormCompanyInfo", "--사업자정보 저장.", None))
        self.actionActionOnButtonUserSave.setText(_translate("FormCompanyInfo", "actionOnButtonUserSave", None))

        self.actionOnButtonEvent.trigger=self.onEventButtonSave
        self.actionActionOnButtonUserSave.trigger=self.onEventButtonUserSave

